

import "@/app/globals.css";
import Navbar from "@/components/Navbar";
import Link from "next/link";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({ children }) {



  return (
    <body>
      <main className="bg-fuchsia-100">
        <Navbar>
          <div className='w-7/12 mx-auto'>
            <ul className='flex justify-evenly'>
              <li>
                <Link href={'new-order'}>سفارش جدید</Link>
              </li>
              <li>
                <Link href={'followed-up'}>پیگیری نشده</Link>
              </li>
              <li>
                <Link href={'not-followed-up'}>پیگیری شده</Link>
              </li>
            </ul>

          </div>
          {children}
        </Navbar>
      </main>
    </body>
  )
}
